[project]
name = "ai-2026-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "accelerate>=1.13.0",
    "apache-airflow[celery]>=3.2.1",
    "bitsandbytes>=0.49.2",
    "boto3>=1.43.5",
    "clickhouse-connect>=0.15.1",
    "config>=0.5.1",
    "datasets>=4.8.5",
    "fastapi>=0.136.1",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.9",
    "numpy>=2.4.3",
    "pandas==2.2.3",
    "peft>=0.19.1",
    "prophet>=1.3.0",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=23.0.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "python-telegram-bot>=22.7",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.3.0",
    "sqlalchemy>2.0.0",
    "sqlglot>=30.7.0",
    "statsforecast>=2.0.3",
    "torch>=2.11.0",
    "tqdm>=4.67.3",
    "transformers>=5.5.0",
    "uvicorn>=0.42.0",
]

[dependency-groups]
airflow = [
    "airflow-clickhouse-plugin>=1.7.0",
    "apache-airflow==3.2.1",
    "apache-airflow-providers-amazon>=9.27.0",
    "apache-airflow-providers-celery>=3.19.0",
    "apache-airflow-providers-postgres>=6.6.3",
    "asyncpg>=0.31.0",
    "clickhouse-connect>=0.15.1",
    "numpy>=2.4.4",
    "pandas>=2.2.3",
    "prophet>=1.3.0",
    "psycopg2-binary>=2.9.12",
    "pyarrow>=24.0.0",
    "scikit-learn>=1.8.0",
    "sqlalchemy>=2.0.49",
    "statsforecast>=2.0.3",
    "tqdm>=4.67.3",
]
anomaly_detection = [
    "fastapy>=1.0.5",
    "numpy>=2.4.4",
    "scikit-learn>=1.8.0",
    "tqdm>=4.67.3",
    "uvicorn>=0.42.0",
]
text_to_sql = [
    "accelerate>=1.13.0",
    "bitsandbytes>=0.49.2",
    "clickhouse-connect>=0.15.1",
    "datasets>=4.8.5",
    "fastapi>=0.136.1",
    "numpy>=2.4.3",
    "peft>=0.19.1",
    "pydantic>=2.12.5",
    "scikit-learn>=1.8.0",
    "sentence-transformers>=5.4.1",
    "sqlglot>=30.7.0",
    "tqdm>=4.67.3",
    "transformers>=5.7.0",
    "uvicorn>=0.42.0",
]
forecasting = [
    "clickhouse-connect>=0.15.1",
    "fastapi>=0.136.1",
    "numpy>=2.4.4",
    "prophet>=1.3.0",
    "pydantic>=2.13.3",
    "scikit-learn>=1.8.0",
    "statsforecast>=2.0.3",
    "tqdm>=4.67.3",
    "uvicorn>=0.42.0",
]
telegram = [
    "clickhouse-connect>=0.15.1",
    "httpx>=0.28.1",
    "matplotlib>=3.10.9",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "python-telegram-bot>=22.7",
]
