#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" \
                        --dbname "postgres" \
  --set AIRFLOW_POSTGRES_PASSWORD="$AIRFLOW_POSTGRES_PASSWORD" \
  --set ADMIN_POSTGRES_PASSWORD="$ADMIN_POSTGRES_PASSWORD" <<-'EOSQL'

CREATE USER airflow WITH PASSWORD :'AIRFLOW_POSTGRES_PASSWORD';
CREATE USER admin WITH PASSWORD :'ADMIN_POSTGRES_PASSWORD';
CREATE DATABASE airflow OWNER airflow;
--CREATE DATABASE seller OWNER admin;

EOSQL