\c seller

CREATE SCHEMA IF NOT EXISTS seller AUTHORIZATION admin;
GRANT USAGE ON SCHEMA seller TO airflow;
GRANT CREATE ON SCHEMA seller TO airflow;

-- Categories
CREATE TABLE IF NOT EXISTS seller.category (
    catalogid TEXT PRIMARY KEY,
    catalogpath JSONB,
    ids BIGINT[],
    source_file TEXT,
    loaded_at TIMESTAMP DEFAULT NOW()
);

-- Items
CREATE TABLE IF NOT EXISTS seller.items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT,
    itemname TEXT,
    attributes JSONB,
    fclip_embed DOUBLE PRECISION[],
    catalogid TEXT REFERENCES category(catalogid) ON DELETE SET NULL,
    variant_id BIGINT,
    model_id BIGINT,
    source_file TEXT,
    loaded_at TIMESTAMP DEFAULT NOW()
);

-- Orders
CREATE TABLE IF NOT EXISTS seller.orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT,
    user_id BIGINT,
    created_timestamp TIMESTAMP,
    last_status TEXT,
    last_status_timestamp TIMESTAMP,
    created_date DATE,
    source_file TEXT,
    loaded_at TIMESTAMP DEFAULT NOW()
);

-- Tracker
CREATE TABLE IF NOT EXISTS seller.tracker (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id TEXT,
    user_id BIGINT,
    timestamp TIMESTAMP,
    action_type TEXT,
    action_widget TEXT,
    date DATE,
    source_file TEXT,
    loaded_at TIMESTAMP DEFAULT NOW()
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA seller TO airflow;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA seller TO airflow;

ALTER DEFAULT PRIVILEGES IN SCHEMA seller GRANT ALL ON TABLES TO airflow;
ALTER DEFAULT PRIVILEGES IN SCHEMA seller GRANT ALL ON SEQUENCES TO airflow;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON seller.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_item_id ON seller.orders(item_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_date ON seller.orders(created_date);
CREATE INDEX IF NOT EXISTS idx_tracker_user_id ON seller.tracker(user_id);
CREATE INDEX IF NOT EXISTS idx_tracker_item_id ON seller.tracker(item_id);
CREATE INDEX IF NOT EXISTS idx_tracker_date ON seller.tracker(date);
CREATE INDEX IF NOT EXISTS idx_items_catalogid ON seller.items(catalogid);

ALTER ROLE admin SET search_path TO seller, public;
ALTER ROLE airflow SET search_path TO seller, public;